
CPP_SRC_FILES := main.cpp
CPP_COMPILE_FLAGS := -g -Wall -Wextra -std=c++23
CPP_PROJ_NAME := pid


main:
	@echo Compiling ${CPP_SRC_FILES}
	g++ ${CPP_COMPILE_FLAGS} ${CPP_SRC_FILES} -o ${CPP_PROJ_NAME}

clean:
	@echo Removing ${CPP_PROJ_NAME}
	@rm ${CPP_PROJ_NAME}

